# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YLHrANyrfHBp-AKUcgbkvr0ymf9gWX5I
"""
#Ho cambiato e ridotto tutto questo file, ho scaricato tutti i pacchetti necessari
import pandas as pd
import os
from sklearn.preprocessing import LabelEncoder as laben
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
import pickle

vectorizer = CountVectorizer()
def elaborazione(message):
  #Carica il dataset
  
  #Carica modello
  phrase = [message]
  X = vectorizer.transform(phrase)
  result = classifier.predict(X)[0]
  return result

dataset = pd.read_csv('News_data_Classification.csv')
path_file = 'Model_Trained_num_iter_3000'

if os.path.exists(path_file):
  classifier = pickle.load(open(path_file, 'rb'))
  X = dataset.iloc[:,[2]].values
  Y = dataset.iloc[:,-2].values
  le = laben()
  Y = le.fit_transform(Y)
  sentence_train, sentence_test,y_train,y_test = train_test_split(X,Y,test_size=0.25, random_state=1000)
  vectorizer.fit(sentence_train.ravel())
else:
    print('rete non trovata')
